### PR TITLE
✨ NEW: Add `solution` directive

### PR DESCRIPTION
**Pull request by najuzilu**
*** **IN PROGRESS** ***

This PR introduces a new `solution` directive. The solution directive will reference an `exercise` directive. The syntax is as follows:

````
```{proof:exercise} Exercise 1
:label: ex1-label

This is an exercise directive.
```

```{proof:solution} ex1-label
This is the solution associated with the above exercise.
```
````
For more information on how this directive behaves, either check the deployed Netlify link below or read through #18.

Additional `algorithm` and `proof` tests have been introduced to take into account any new changes introduced with the new directive. These tests include:
- _algo_title_with_inline_math
- _algo_with_labeled_math
- _algo_unlabeled_math
- _proof_inline_math_argument

**Solution** tests include:
- [x] `solution` with an enumerable `exercise`
- [x] `solution` with an unenumerable + simple title `exercise`
- [x] `solution` with an unenumerable+ inline-math title `exercise`
- [x] `solution` with an unenumerable + not titled `exercise`
- [x] `solution` missing its argument
- [x] `solution` where the argument is incorrect `exercise` label
- [x] `solution` using `label` and `class` options
- [x] `solution` referencing an enumerable `exercise`
- [x] `solution` referencing an unenumerable + simple title `exercise`
- [x] `solution` referencing an unenumerable + inline-math title `exercise`
- [x] `solution` referencing an unenumerable + not titled `exercise`
- [x] `solution` referencing incorrect `solution` label
- [x] `solution` with duplicate label

### CODE REVIEW

**Comment by najuzilu** [comment]
@AakashGfude maybe you'll be able to provide some guidance regarding the warning test for the solution directive. It doesn't look like `rootdir` method is executed at all during warnings which could explain why `warnings(app)` returns an empty string (the `dst` directory isn't removed prior to build...).

The strange thing is that when I run `pytest tests/test_solution.py --verbose`, all the tests pass. The `test_warnings` method fails with the overall `pytest --verbose`. Do you have any suggestions as to how to proceed?

**Comment by AakashGfude** [comment]
Hey @najuzilu , sorry missed this comment. I guess it is the same thing you talked about on slack and is now solved?

**Comment by najuzilu** [comment]
Yes, when `app.build()` is initiated in the `test_warnings` method of `test_solution.py`, mybook doesn't display any warnings because it has been previously built (during `test_algorithm.py`). In order for warnings to display, I have to remove the `_build` directory and then build. I'll likely move this under the `rootdir` method to initiate a clean build every time for all tests which should minimize errors like this in the future.

**Comment by najuzilu** [comment]
@mmcky @AakashGfude I plan to rebase before merging haha.

**Comment by najuzilu** [comment]
The new refactored code allows for easier implementation of other directives which behave similarly to `solution`. I decided to move the implementation to a new `LinkedDirective` with supporting `linked_node` object and `visit_linked_node, depart_linked_node` methods.

**Comment by choldgraf** [comment]
this is really cool! One question - how "proof-specific" is this functionality? I ask because [question and answer directives](https://github.com/executablebooks/jupyter-book/issues/536) are one of the more-requested features in jupyter book, and I wonder if it's worth generalizing this a bit so that you can use it outside of the context of proofs. What do you all think?

**Comment by jstac** [comment]
@mmcky made the same point.  

Of course there's nothing stopping people using the solutions / exercises without using any of the theorem / proof / lemma environments.  But I guess your point is the name of the package will confuse people, so perhaps the solutions / exercises should be broken out into something separate?  Or should the package itself be renamed?

I agree that the solutions / exercises environments will be popular on their own.

**Comment by choldgraf** [comment]
yeah I was imagining if this is a generically-useful directive, we could split it out into something like `sphinx-exercise` (or `sphinxcontrib-exercise` if @mmcky prefers ;-) ) and then prettyproof could _use_ that package, but it would be more generically useful (and easier for people to discover and use)

**Comment by jstac** [comment]
I'm fully in favor of this.  @najuzilu has done some really nice work here, worthy of two extensions `:-)`

**Comment by najuzilu** [comment]
Ah yes, we plan to move these over to a new repo. I've already started some work on that. 

My main goal is to get this to work correctly with the current infrastructure. It will be very easy to migrate it to `sphinx-exercise` (shorter is better in my opinion). I'll open an issue regarding this once we merge the PR successfully. How does that sound? @choldgraf

**Comment by choldgraf** [comment]
@najuzilu that works for me - though we should make the switch relatively quickly because I imagine there will be an API deprecation (as presumably people would just use ` ```{solution} ` rather than ` ```{proof:solution} `

**Comment by mmcky** [comment]
thanks @jstac -- @najuzilu let us know if you need any help setting up the new repo. Looking forward to `sphinx-exercise`. Also given we have `just` transferred this over to `ebp` would you like to keep this package as `sphinxcontrib` or move it to a similar naming convention `sphinx-` or `sphinxext-`

**Comment by choldgraf** [comment]
my preference is for `sphinx-` but I'm happy with either...I always found the `sphinxcontrib` thing for independent repos to be a bit weird because [it's not part of the sphinxcontrib org](https://github.com/sphinx-contrib), but IMO it's not a huge deal either way.

**Comment by mmcky** [comment]
> my preference is for `sphinx-` but I'm happy with either...I always found the `sphinxcontrib` thing for independent repos to be a bit weird because [it's not part of the sphinxcontrib org](https://github.com/sphinx-contrib), but IMO it's not a huge deal either way.

👍 let's use `sphinx-` for sphinx extensions in `ebp`. I agree and in favour of this. As you say it isn't part of the formal `sphinxcontrib` community.

**Comment by najuzilu** [comment]
If everyone's okay with it, I'm going to go ahead and close this PR as I've transferred over the work to [sphinx-exercise](https://github.com/najuzilu/sphinx-exercise). I have already made a PR to depreciate immediately the `exercise` directive which has also been migrated to  [sphinx-exercise](https://github.com/najuzilu/sphinx-exercise).

**Pull request closed without merging**
